steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_TURNSTILE_SITE_KEY=${_NEXT_PUBLIC_TURNSTILE_SITE_KEY}'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/field-notes/turbulent-frontend'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/field-notes/turbulent-frontend'
substitutions:
  _NEXT_PUBLIC_API_URL: ''
  _NEXT_PUBLIC_TURNSTILE_SITE_KEY: ''
