steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '--build-arg'
      - 'UNSAFE_EVAL=${_UNSAFE_EVAL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/turbulent-frontend'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/turbulent-frontend'
substitutions:
  _NEXT_PUBLIC_API_URL: ''
  _UNSAFE_EVAL: ''
