steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'INSTALL_FFMPEG=${_INSTALL_FFMPEG}'
      - '-f'
      - 'backend/Dockerfile'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/field-notes/turbulent-service'
      - '.'
substitutions:
  _INSTALL_FFMPEG: 'false'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/field-notes/turbulent-service'
