steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'INSTALL_FFMPEG=${_INSTALL_FFMPEG}'
      - '-f'
      - 'backend/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/turbulent-service'
      - '.'
substitutions:
  _INSTALL_FFMPEG: 'false'
images:
  - 'gcr.io/$PROJECT_ID/turbulent-service'
