steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'cloud-functions/video-processor/Dockerfile'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/field-notes/video-processor'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/field-notes/video-processor'
